GET http://localhost:3000/api/peliculas

###

GET http://localhost:3000/api/peliculas?titulo=Dun

###

GET http://localhost:3000/api/peliculas?anio=2024

###

GET http://localhost:3000/api/peliculas?titulo=Dun&anio=2000

###

GET http://localhost:3000/api/peliculas/2

###

POST http://localhost:3000/api/peliculas
Content-Type: application/json

{
    "titulo": "Película de prueba",
    "sinopsis": "Sinopsis de prueba.",
    "anio": 2024,
    "poster": "Sin poster",
    "categorias": [2, 3]
}

###

POST http://localhost:3000/api/peliculas
Content-Type: application/json

{
    "titulo": "Película de prueba 1",
    "sinopsis": "Sinopsis de prueba 1.",
    "anio": 2022,
    "poster": "Sin poster",
    "categorias": [5, 3]
}

###

POST http://localhost:3000/api/peliculas
Content-Type: application/json

{
    "titulo": "Película de prueba 2",
    "sinopsis": "Sinopsis de prueba 2.",
    "anio": 2021,
    "poster": "Sin poster",
    "categorias": [4, 7]
}

###

POST http://localhost:3000/api/peliculas
Content-Type: application/json

{
    "titulo": "Película de prueba 3",
    "sinopsis": "Sinopsis de prueba 3.",
    "anio": 2023,
    "poster": "Sin poster",
    "categorias": [6, 3]
}

###

PUT http://localhost:3000/api/peliculas/16
Content-Type: application/json

{
    "peliculaid": 16,
    "titulo": "Paw Patrol: La Súper Película",
    "sinopsis": "Un meteorito mágico aterriza en Adventure City y otorga superpoderes a los cachorros de PAW Patrol, convirtiéndolos en The Mighty Pups.",
    "anio": 2024,
    "poster": "http://m.media-amazon.com/images/M/MV5BMGI4NTNlODItMGJlZi00OTIwLTlkM2ItMWFkZjJhZDIzMDc3XkEyXkFqcGdeQXVyMTEyNzQ1MTk0._V1_SX300.jpg",
    "categorias": [1, 2, 3]
}

###

DELETE http://localhost:3000/api/peliculas/16