GET http://localhost:3000/api/usuarios?nombrerol=Administrador

### 

POST http://localhost:3000/api/usuarios
Content-Type: application/json

{
    "email": "john.doe@email.com",
    "password": "passwordSeguro",
    "nombre": "John Doe",
    "rol": "Usuario"
}

###

PUT http://localhost:3000/api/usuarios/john.doe@email.com
Content-Type: application/json

{   
    "nombre": "John Doe Editado",
    "rol": "Usuario"
}

### 

DELETE http://localhost:3000/api/usuarios/john.doe@email.com

###

POST http://localhost:3000/api/auth
Content-Type: application/json

{
    "email": "gvera@uv.mx",
    "password": "patito"
}

###

POST http://localhost:3000/api/auth
Content-Type: 

{
    "email": "patito@uv.mx",
    "password": "patito"

}